#!/bin/sh

if [ $# -lt 2 ]; then
    echo >&2 "Usage: $0 PATH LINKTARGET"
    exit 1
fi

path="$1"
path="${path#~/}"
path="${path#$HOME/}"
target="$2"
if [ -d "$target" ]; then
    path="${path%/}/"
fi
target="${target#~/}"
target="${target#$HOME/}"
target="${target%/}"


printf "%s -> %s\n" "$target" "$path"
printf "%s\t%s\n" "$path" "$target" >>Links.txt
sort -u Links.txt > Links.txt.new && mv Links.txt.new Links.txt
