#!/bin/sh

if [ $# -lt 1 ]; then
    echo >&2 "Usage: ${0##*/} DROPBOX_SUBDIR APPLICATION_SUPPORT_SUBDIR"
    exit 2
fi

dropboxdir="$1"
appsupdir="${2:-$1}"

exec "$(dirname "$0")/add" Dropbox/Games/"$dropboxdir"/ Library/Application\ Support/"$appsupdir"
