#!/bin/sh

find ~/Documents/ \( -iname \$RECYCLE.BIN -o -iname RECYCLER -o -iname \*.localized -o -iname .prl_\* -prune \) -o \( -type f -not -iname .DS_Store -not -iname desktop.ini -not -iname Thumbs.db -not -iname \*.strings -not -iname \*.log -not -iname \*log.txt -print \)
