#!/bin/sh

find ~/Documents/ \( -name \$RECYCLE.BIN -o -name RECYCLER -o -name \*.localized -o -name .prl_\* -prune \) -o \( -type f -not -name .DS_Store -not -name desktop.ini -not -name Thumbs.db -not -name \*.strings -print \)
