#!/bin/sh

if [ "$PWD" = "$HOME" ]; then
    exit 3
fi

link () {
    mkdir -p "${1%/*}"
    rm -f "$1"
    ln -s "$2" "$1"
}

dest="$PWD"
orig_dest="$HOME"

while IFS="	" read filename from_pattern to_pattern; do
    if [ ! -e "$filename" ]; then
        continue
    fi

    grep -v "^#" "$filename" | while IFS="	" read to_path from_path; do
        if [ -z "$from_path" ]; then
            from_path="$to_path"
        fi

        if [ -z "$to_path" ]; then
            continue
        fi

        full_from="$(printf "$from_pattern" "$from_path")"
        full_to="$(printf "$to_pattern" "$to_path")"

        if [ ! -e "$dest/$full_to" ]; then
            if [ -n "$orig_dest" ] && [ "$dest" != "$orig_dest" ]; then
                if [ -e "$orig_dest/$full_from" ]; then
                    echo "Found $full_from in $orig_dest, copying"
                    dest_to="$dest/$full_to"
                    mkdir -p "${dest_to%/*}"
                    cp -a "$orig_dest/$full_from" "$dest/$full_to"
                elif [ -e "$orig_dest/$full_from.zip" ]; then
                    echo "Found $full_from.zip in $orig_dest, extracting"
                    dest_to="$dest/$full_to"
                    mkdir -p "${dest_to%/*}"
                    cd "$dest/${full_to%/*}"
                    unzip "$orig_dest/$full_from.zip" >/dev/null
                    cd - >/dev/null
                elif [ -e "$orig_dest/$full_from.7z" ]; then
                    echo "Found $full_from.7z in $orig_dest, extracting"
                    dest_to="$dest/$full_to"
                    mkdir -p "${dest_to%/*}"
                    cd "$dest/${full_to%/*}"
                    7z x "$orig_dest/$full_from.7z" >/dev/null
                    cd - >/dev/null
                else
                    echo >&2 "Warning: $orig_dest/$full_from does not exist, skipping"
                fi
            else
                echo >&2 "Warning: $dest/$full_to does not exist, skipping"
            fi
        elif [ ! -h "$dest/$full_to" ]; then
            echo >&2 "Warning: destination $dest/$full_to already exists and is not a symlink"
        fi

        link "$dest/$full_from" "$dest/$full_to"
    done
done <<END
Links.txt	%s	%s
DropboxLinks.txt       %s      Dropbox/%s
DropboxGames.txt       Documents/%s    Dropbox/Games/%s
DropboxApps.txt        Documents/%s    Dropbox/Apps/%s
END
